'use client';

import { useMemo, useState } from 'react';
import { Cpu, Check, Copy, FileCode, Layers, Plus, Trash2 } from 'lucide-react';
import { cn } from '@/lib/utils';

type Region = {
  id: string;
  name: string;
  start: string; // hex string e.g. "0x08000000"
  sizeKB: number;
  rwx: string; // e.g. "rx", "rwx", "rw"
};

type Preset = {
  label: string;
  cpu: string;
  regions: Region[];
  stackKB: number;
  heapKB: number;
  stackRegion: string;
  vectorRegion: string;
};

const presets: Preset[] = [
  {
    label: 'STM32F411 (M4F, 512K flash, 128K SRAM)',
    cpu: 'cortex-m4',
    regions: [
      { id: 'flash', name: 'FLASH', start: '0x08000000', sizeKB: 512, rwx: 'rx' },
      { id: 'ram',   name: 'RAM',   start: '0x20000000', sizeKB: 128, rwx: 'rwx' },
    ],
    stackKB: 4,
    heapKB: 2,
    stackRegion: 'RAM',
    vectorRegion: 'FLASH',
  },
  {
    label: 'STM32H743 (M7, 2M flash, ITCM+DTCM+SRAM)',
    cpu: 'cortex-m7',
    regions: [
      { id: 'flash', name: 'FLASH', start: '0x08000000', sizeKB: 2048, rwx: 'rx' },
      { id: 'itcm',  name: 'ITCM',  start: '0x00000000', sizeKB: 64,   rwx: 'rx' },
      { id: 'dtcm',  name: 'DTCM',  start: '0x20000000', sizeKB: 128,  rwx: 'rwx' },
      { id: 'ram',   name: 'RAM',   start: '0x24000000', sizeKB: 512,  rwx: 'rwx' },
    ],
    stackKB: 16,
    heapKB: 8,
    stackRegion: 'DTCM',
    vectorRegion: 'FLASH',
  },
  {
    label: 'nRF52840 (M4F, 1M flash, 256K RAM)',
    cpu: 'cortex-m4',
    regions: [
      { id: 'flash', name: 'FLASH', start: '0x00000000', sizeKB: 1024, rwx: 'rx' },
      { id: 'ram',   name: 'RAM',   start: '0x20000000', sizeKB: 256,  rwx: 'rwx' },
    ],
    stackKB: 8,
    heapKB: 4,
    stackRegion: 'RAM',
    vectorRegion: 'FLASH',
  },
  {
    label: 'RP2040 (M0+, XIP flash, 264K SRAM)',
    cpu: 'cortex-m0plus',
    regions: [
      { id: 'flash', name: 'FLASH', start: '0x10000000', sizeKB: 2048, rwx: 'rx' },
      { id: 'ram',   name: 'RAM',   start: '0x20000000', sizeKB: 264,  rwx: 'rwx' },
    ],
    stackKB: 4,
    heapKB: 2,
    stackRegion: 'RAM',
    vectorRegion: 'FLASH',
  },
];

function hexNorm(s: string) {
  if (!s.startsWith('0x') && !s.startsWith('0X')) return s;
  return s.toLowerCase();
}

function genScript(opts: {
  cpu: string;
  regions: Region[];
  stackKB: number;
  heapKB: number;
  stackRegion: string;
  vectorRegion: string;
  cppSupport: boolean;
}) {
  const { cpu, regions, stackKB, heapKB, stackRegion, vectorRegion, cppSupport } = opts;

  const memoryLines = regions
    .map((r) => {
      const start = hexNorm(r.start);
      const size = `${r.sizeKB}K`;
      return `  ${r.name.padEnd(8)}(${r.rwx.padEnd(3)}) : ORIGIN = ${start}, LENGTH = ${size}`;
    })
    .join('\n');

  const stackEnd = (() => {
    const r = regions.find((x) => x.name === stackRegion);
    if (!r) return '0';
    return `ORIGIN(${stackRegion}) + LENGTH(${stackRegion})`;
  })();

  const ctorsDtors = cppSupport
    ? `
    /* C++ static constructors */
    . = ALIGN(4);
    KEEP(*(.init))
    KEEP(*(.fini))
    . = ALIGN(4);
    __preinit_array_start = .;
    KEEP(*(.preinit_array))
    __preinit_array_end = .;
    . = ALIGN(4);
    __init_array_start = .;
    KEEP(*(SORT(.init_array.*)))
    KEEP(*(.init_array))
    __init_array_end = .;
    . = ALIGN(4);
    __fini_array_start = .;
    KEEP(*(SORT(.fini_array.*)))
    KEEP(*(.fini_array))
    __fini_array_end = .;
`
    : '';

  return `/* Linker script generated by armhub.dev linker-script tool
 * CPU: ${cpu}
 * Stack region: ${stackRegion} (${stackKB}K)
 * Heap size: ${heapKB}K
 * Vector table region: ${vectorRegion}
 */

ENTRY(Reset_Handler)

/* Highest address of the user mode stack */
_estack = ${stackEnd};

/* Required amounts of heap and stack */
_Min_Heap_Size  = 0x${(heapKB * 1024).toString(16).toUpperCase()};  /* ${heapKB} KiB */
_Min_Stack_Size = 0x${(stackKB * 1024).toString(16).toUpperCase()};  /* ${stackKB} KiB */

MEMORY
{
${memoryLines}
}

SECTIONS
{
  /* --- Vector table + code + read-only data --- */
  .isr_vector :
  {
    . = ALIGN(4);
    KEEP(*(.isr_vector))
    . = ALIGN(4);
  } >${vectorRegion}

  .text :
  {
    . = ALIGN(4);
    *(.text)
    *(.text*)
    *(.glue_7)         /* ARM/Thumb interworking veneers */
    *(.glue_7t)
    *(.eh_frame)
${ctorsDtors}
    . = ALIGN(4);
    _etext = .;
  } >${vectorRegion}

  .rodata :
  {
    . = ALIGN(4);
    *(.rodata)
    *(.rodata*)
    . = ALIGN(4);
  } >${vectorRegion}

  .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } >${vectorRegion}
  .ARM       : {
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  } >${vectorRegion}

  /* --- Initialized data: load address in flash, run address in RAM --- */
  _sidata = LOADADDR(.data);

  .data :
  {
    . = ALIGN(4);
    _sdata = .;
    *(.data)
    *(.data*)
    *(.RamFunc)        /* code that runs from RAM */
    *(.RamFunc*)
    . = ALIGN(4);
    _edata = .;
  } >RAM AT> ${vectorRegion}

  /* --- Zero-initialized BSS --- */
  .bss :
  {
    . = ALIGN(4);
    _sbss = .;
    __bss_start__ = _sbss;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
    __bss_end__ = _ebss;
  } >RAM

  /* --- User heap & stack: keep them in the stack region, fail at link if too small --- */
  ._user_heap_stack :
  {
    . = ALIGN(8);
    PROVIDE ( end = . );
    PROVIDE ( _end = . );
    . = . + _Min_Heap_Size;
    . = . + _Min_Stack_Size;
    . = ALIGN(8);
  } >${stackRegion}

  /DISCARD/ :
  {
    libc.a ( * )
    libm.a ( * )
    libgcc.a ( * )
  }

  .ARM.attributes 0 : { *(.ARM.attributes) }
}
`;
}

function uid() {
  return Math.random().toString(36).slice(2, 9);
}

export function LinkerScript() {
  const [presetIdx, setPresetIdx] = useState(0);
  const [cpu, setCpu] = useState(presets[0].cpu);
  const [regions, setRegions] = useState<Region[]>(() => presets[0].regions.map((r) => ({ ...r })));
  const [stackKB, setStackKB] = useState(presets[0].stackKB);
  const [heapKB, setHeapKB] = useState(presets[0].heapKB);
  const [stackRegion, setStackRegion] = useState(presets[0].stackRegion);
  const [vectorRegion, setVectorRegion] = useState(presets[0].vectorRegion);
  const [cppSupport, setCppSupport] = useState(true);
  const [copied, setCopied] = useState(false);

  const applyPreset = (idx: number) => {
    const p = presets[idx];
    setPresetIdx(idx);
    setCpu(p.cpu);
    setRegions(p.regions.map((r) => ({ ...r })));
    setStackKB(p.stackKB);
    setHeapKB(p.heapKB);
    setStackRegion(p.stackRegion);
    setVectorRegion(p.vectorRegion);
  };

  const updateRegion = (id: string, patch: Partial<Region>) => {
    setRegions((rs) => rs.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  };

  const removeRegion = (id: string) => {
    setRegions((rs) => rs.filter((r) => r.id !== id));
  };

  const addRegion = () => {
    setRegions((rs) => [
      ...rs,
      { id: uid(), name: `MEM${rs.length}`, start: '0x20000000', sizeKB: 64, rwx: 'rwx' },
    ]);
  };

  const regionNames = regions.map((r) => r.name);
  // keep selectors valid even if a region is removed/renamed
  const stackRegionSafe = regionNames.includes(stackRegion) ? stackRegion : regionNames[0] ?? '';
  const vectorRegionSafe = regionNames.includes(vectorRegion) ? vectorRegion : regionNames[0] ?? '';

  const script = useMemo(
    () =>
      genScript({
        cpu,
        regions,
        stackKB,
        heapKB,
        stackRegion: stackRegionSafe,
        vectorRegion: vectorRegionSafe,
        cppSupport,
      }),
    [cpu, regions, stackKB, heapKB, stackRegionSafe, vectorRegionSafe, cppSupport],
  );

  const totalKB = regions.reduce((a, r) => a + r.sizeKB, 0);

  const copyScript = async () => {
    try {
      await navigator.clipboard.writeText(script);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      // ignore
    }
  };

  return (
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]">
      {/* --- LEFT: CONFIG --- */}
      <div className="space-y-4 lg:sticky lg:top-20 lg:self-start">
        <div className="rounded-lg border bg-card p-4 sm:p-5">
          <div className="mb-3 flex items-center gap-2 text-sm font-semibold">
            <Cpu className="h-4 w-4" />
            <span>Preset</span>
          </div>
          <div className="grid gap-1.5">
            {presets.map((p, i) => (
              <button
                key={p.label}
                type="button"
                onClick={() => applyPreset(i)}
                className={cn(
                  'rounded-md border px-3 py-2 text-left text-xs transition-colors',
                  presetIdx === i
                    ? 'border-primary/40 bg-primary/10 text-foreground'
                    : 'border-border bg-card/60 text-muted-foreground hover:border-primary/30 hover:text-foreground',
                )}
              >
                <div className="font-medium">{p.label}</div>
                <div className="mt-0.5 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">
                  {p.cpu} · stack {p.stackKB}K in {p.stackRegion}
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className="rounded-lg border bg-card p-4 sm:p-5">
          <div className="mb-3 flex items-center justify-between gap-2">
            <div className="text-sm font-semibold">Memory regions</div>
            <div className="font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">
              total {totalKB}K
            </div>
          </div>
          <div className="space-y-2">
            {regions.map((r) => (
              <div key={r.id} className="grid grid-cols-[1fr_1fr_auto_auto] items-center gap-2 rounded-md border bg-card/60 p-2">
                <input
                  value={r.name}
                  onChange={(e) => updateRegion(r.id, { name: e.target.value.replace(/\s+/g, '').toUpperCase() })}
                  className="rounded border bg-background px-2 py-1 font-mono text-[0.7rem] uppercase tracking-wider"
                  aria-label="Region name"
                />
                <input
                  value={r.start}
                  onChange={(e) => updateRegion(r.id, { start: e.target.value.trim() })}
                  className="rounded border bg-background px-2 py-1 font-mono text-[0.7rem] lowercase"
                  aria-label="Origin address"
                  placeholder="0x08000000"
                />
                <div className="flex items-center gap-1">
                  <input
                    type="number"
                    value={r.sizeKB}
                    min={1}
                    onChange={(e) => updateRegion(r.id, { sizeKB: Math.max(1, Number(e.target.value) || 0) })}
                    className="w-20 rounded border bg-background px-2 py-1 font-mono text-[0.7rem]"
                    aria-label="Size in KB"
                  />
                  <span className="font-mono text-[0.6rem] uppercase tracking-wider text-muted-foreground">KB</span>
                </div>
                <div className="flex items-center gap-1">
                  <select
                    value={r.rwx}
                    onChange={(e) => updateRegion(r.id, { rwx: e.target.value })}
                    className="rounded border bg-background px-1.5 py-1 font-mono text-[0.65rem] uppercase tracking-wider"
                    aria-label="Permissions"
                  >
                    <option value="rx">rx</option>
                    <option value="rw">rw</option>
                    <option value="rwx">rwx</option>
                  </select>
                  <button
                    type="button"
                    onClick={() => removeRegion(r.id)}
                    aria-label={`Remove ${r.name}`}
                    className="grid h-7 w-7 place-items-center rounded border bg-card text-muted-foreground hover:border-destructive/30 hover:text-destructive"
                  >
                    <Trash2 className="h-3 w-3" />
                  </button>
                </div>
              </div>
            ))}
          </div>
          <button
            type="button"
            onClick={addRegion}
            className="mt-2 inline-flex items-center gap-1.5 rounded-md border bg-card/60 px-2.5 py-1.5 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground hover:border-primary/30 hover:text-foreground"
          >
            <Plus className="h-3 w-3" /> Add region
          </button>
        </div>

        <div className="rounded-lg border bg-card p-4 sm:p-5">
          <div className="mb-3 text-sm font-semibold">Layout</div>
          <div className="space-y-3">
            <label className="block">
              <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">CPU</div>
              <input
                value={cpu}
                onChange={(e) => setCpu(e.target.value)}
                className="w-full rounded border bg-background px-2 py-1.5 font-mono text-xs"
                placeholder="cortex-m4"
              />
            </label>
            <div className="grid grid-cols-2 gap-2">
              <label className="block">
                <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">Vector / code</div>
                <select
                  value={vectorRegionSafe}
                  onChange={(e) => setVectorRegion(e.target.value)}
                  className="w-full rounded border bg-background px-2 py-1.5 font-mono text-xs"
                >
                  {regions.map((r) => (
                    <option key={r.id} value={r.name}>
                      {r.name}
                    </option>
                  ))}
                </select>
              </label>
              <label className="block">
                <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">Stack region</div>
                <select
                  value={stackRegionSafe}
                  onChange={(e) => setStackRegion(e.target.value)}
                  className="w-full rounded border bg-background px-2 py-1.5 font-mono text-xs"
                >
                  {regions.map((r) => (
                    <option key={r.id} value={r.name}>
                      {r.name}
                    </option>
                  ))}
                </select>
              </label>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <label className="block">
                <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">Stack (KB)</div>
                <input
                  type="number"
                  value={stackKB}
                  min={1}
                  onChange={(e) => setStackKB(Math.max(1, Number(e.target.value) || 0))}
                  className="w-full rounded border bg-background px-2 py-1.5 font-mono text-xs"
                />
              </label>
              <label className="block">
                <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">Heap (KB)</div>
                <input
                  type="number"
                  value={heapKB}
                  min={0}
                  onChange={(e) => setHeapKB(Math.max(0, Number(e.target.value) || 0))}
                  className="w-full rounded border bg-background px-2 py-1.5 font-mono text-xs"
                />
              </label>
            </div>
            <label className="flex items-center gap-2 text-xs">
              <input
                type="checkbox"
                checked={cppSupport}
                onChange={(e) => setCppSupport(e.target.checked)}
                className="h-3.5 w-3.5"
              />
              <span>Include C++ ctor/dtor arrays (.init_array / .fini_array)</span>
            </label>
          </div>
        </div>
      </div>

      {/* --- RIGHT: OUTPUT --- */}
      <div className="space-y-4">
        <div className="rounded-lg border bg-card p-4 sm:p-5">
          <div className="mb-3 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <FileCode className="h-4 w-4" />
              <span>Generated linker.ld</span>
            </div>
            <button
              type="button"
              onClick={copyScript}
              className={cn(
                'inline-flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 font-mono text-[0.65rem] uppercase tracking-wider transition-colors',
                copied
                  ? 'border-primary/40 bg-primary/10 text-primary'
                  : 'border-border bg-card/60 text-muted-foreground hover:border-primary/30 hover:text-foreground',
              )}
            >
              {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="overflow-x-auto rounded-md border bg-muted/30 p-3 font-mono text-[0.72rem] leading-relaxed">
            <code>{script}</code>
          </pre>
        </div>

        <div className="rounded-lg border bg-card p-4 sm:p-5 text-xs text-muted-foreground leading-relaxed">
          <div className="mb-1 font-mono text-[0.65rem] uppercase tracking-wider text-foreground">How to use</div>
          <ol className="ml-4 list-decimal space-y-1">
            <li>Save as <code className="font-mono text-foreground">linker.ld</code> in your project.</li>
            <li>Pass it to GCC with <code className="font-mono text-foreground">-T linker.ld</code>.</li>
            <li>In your startup file, set <code className="font-mono text-foreground">_estack</code> as the initial SP in the vector table — it&apos;s defined here as the top of the stack region.</li>
            <li>Your reset handler must zero <code className="font-mono text-foreground">.bss</code> (from <code className="font-mono text-foreground">_sbss</code> to <code className="font-mono text-foreground">_ebss</code>) and copy <code className="font-mono text-foreground">.data</code> from <code className="font-mono text-foreground">_sidata</code> to <code className="font-mono text-foreground">_sdata..._edata</code>.</li>
          </ol>
          <div className="mt-3 flex items-center gap-2 font-mono text-[0.65rem] uppercase tracking-wider text-muted-foreground">
            <Layers className="h-3 w-3" />
            <span>Stack ends at top of {stackRegionSafe} — grows down toward <code className="text-foreground">_end</code>.</span>
          </div>
        </div>
      </div>
    </div>
  );
}
