export type NavLink = {
  title: string;
  href: string;
  badge?: string;
  /** Renders indented under the preceding link (e.g. tutorial lessons under their landing). */
  nested?: boolean;
  /** Group key — pager prev/next stays inside the group instead of bleeding into sibling links. */
  group?: string;
};
export type NavSection = { title: string; key: string; intro: string; links: NavLink[] };

export const sections: NavSection[] = [
  {
    title: 'Architecture',
    key: 'architecture',
    intro: 'ARMv6-M through ARMv9-A. Pipelines, modes, exception models, memory ordering, security extensions.',
    links: [
      { title: 'ARM ISA family', href: '/docs/architecture/isa-family' },
      { title: 'AAPCS & calling conventions', href: '/docs/architecture/aapcs' },
      { title: 'ARMv6-M', href: '/docs/architecture/armv6m' },
      { title: 'ARMv7-M', href: '/docs/architecture/armv7m' },
      { title: 'ARMv8-M', href: '/docs/architecture/armv8m', badge: 'v8-M' },
      { title: 'ARMv8-R', href: '/docs/architecture/armv8r' },
      { title: 'ARMv7-M & ARMv8-M (compare)', href: '/docs/architecture/armv7m-armv8m' },
      { title: 'Exception model', href: '/docs/architecture/exception-model' },
      { title: 'Memory model & barriers', href: '/docs/architecture/memory-model' },
      { title: 'Exclusive monitors', href: '/docs/architecture/exclusive-monitors' },
      { title: 'TrustZone', href: '/docs/architecture/trustzone', badge: 'security' },
      { title: 'TrustZone-M deep dive', href: '/docs/architecture/trustzone-m' },
      { title: 'Debug architecture', href: '/docs/architecture/debug' },
      { title: 'Performance monitoring (PMU)', href: '/docs/architecture/pmu' },
      { title: 'PAC, BTI, MTE (v8.x-A)', href: '/docs/architecture/pac-bti-mte' },
    ],
  },
  {
    title: 'Cortex-M',
    key: 'cortex-m',
    intro: 'Microcontroller-class cores — M0 through M85. Real-time, deterministic, deeply embedded.',
    links: [
      { title: 'Core lineup', href: '/docs/cortex-m/lineup' },
      { title: 'Architecture family compared', href: '/docs/cortex-m/architecture-compare' },
      { title: 'Cortex-M0', href: '/docs/cortex-m/m0' },
      { title: 'Cortex-M0+', href: '/docs/cortex-m/m0plus' },
      { title: 'Cortex-M3', href: '/docs/cortex-m/m3' },
      { title: 'Cortex-M4', href: '/docs/cortex-m/m4' },
      { title: 'Cortex-M7', href: '/docs/cortex-m/m7' },
      { title: 'Cortex-M23', href: '/docs/cortex-m/m23', badge: 'v8-M' },
      { title: 'Cortex-M33', href: '/docs/cortex-m/m33', badge: 'v8-M' },
      { title: 'Cortex-M55', href: '/docs/cortex-m/m55', badge: 'Helium' },
      { title: 'Cortex-M85', href: '/docs/cortex-m/m85', badge: 'Helium' },
      { title: 'NVIC overview', href: '/docs/cortex-m/nvic' },
      { title: 'NVIC registers', href: '/docs/cortex-m/nvic-registers' },
      { title: 'NVIC priority & preemption', href: '/docs/cortex-m/nvic-priority' },
      { title: 'Tail-chain & late-arrival', href: '/docs/cortex-m/tail-chain' },
      { title: 'Vector table', href: '/docs/cortex-m/vector-table' },
      { title: 'SysTick & timing', href: '/docs/cortex-m/systick' },
      { title: 'SCB — System Control Block', href: '/docs/cortex-m/scb' },
      { title: 'MPU on Cortex-M', href: '/docs/cortex-m/mpu' },
      { title: 'FPU on Cortex-M', href: '/docs/cortex-m/fpu' },
      { title: 'Cache & TCM (M7/M55/M85)', href: '/docs/cortex-m/cache-tcm' },
      { title: 'DWT / ITM / ETM', href: '/docs/cortex-m/dwt-itm-etm' },
      { title: 'CoreSight', href: '/docs/cortex-m/coresight' },
      { title: 'Low-power modes', href: '/docs/cortex-m/low-power' },
    ],
  },
  {
    title: 'Cortex-A',
    key: 'cortex-a',
    intro: 'Applications-class cores running rich operating systems. MMU, caches, SMP, virtualization.',
    links: [
      { title: 'Cortex-A overview', href: '/docs/cortex-a/overview' },
      { title: 'ARMv7-A vs ARMv8-A vs ARMv9-A', href: '/docs/cortex-a/isa-compare' },
      { title: 'Boot flow & EL levels', href: '/docs/cortex-a/boot-and-exception-levels' },
      { title: 'MMU & paging', href: '/docs/cortex-a/mmu' },
      { title: 'TLB & address translation', href: '/docs/cortex-a/tlb' },
      { title: 'Caches & coherency', href: '/docs/cortex-a/caches' },
      { title: 'GIC — generic interrupt controller', href: '/docs/cortex-a/gic' },
      { title: 'NEON & SVE', href: '/docs/cortex-a/neon-sve' },
      { title: 'SMP & multiprocessing', href: '/docs/cortex-a/smp' },
      { title: 'Virtualization (EL2 / hypervisors)', href: '/docs/cortex-a/virtualization' },
      { title: 'big.LITTLE & DynamIQ', href: '/docs/cortex-a/big-little' },
      { title: 'PMU & profiling', href: '/docs/cortex-a/pmu' },
    ],
  },
  {
    title: 'Cortex-R',
    key: 'cortex-r',
    intro: 'Hard real-time, safety-critical. Lockstep cores, MPUs, tightly coupled memories.',
    links: [
      { title: 'Cortex-R overview', href: '/docs/cortex-r/overview' },
      { title: 'ARMv7-R vs ARMv8-R', href: '/docs/cortex-r/isa-compare' },
      { title: 'Lockstep & ASIL', href: '/docs/cortex-r/lockstep' },
      { title: 'MPU & TCM on Cortex-R', href: '/docs/cortex-r/mpu-tcm' },
      { title: 'Vectored interrupts', href: '/docs/cortex-r/interrupts' },
      { title: 'ECC & error detection', href: '/docs/cortex-r/ecc' },
      { title: 'Safety standards (ISO 26262 / IEC 61508)', href: '/docs/cortex-r/safety-standards' },
      { title: 'Cortex-R52 cluster mode', href: '/docs/cortex-r/r52-cluster' },
    ],
  },
  {
    title: 'Peripherals',
    key: 'peripherals',
    intro: 'GPIO, UART, SPI, I²C, CAN, USB, Ethernet, DMA, ADC/DAC, timers — pattern-by-pattern.',
    links: [
      { title: 'GPIO', href: '/docs/peripherals/gpio' },
      { title: 'GPIO alternate functions & drive', href: '/docs/peripherals/gpio-af' },
      { title: 'UART', href: '/docs/peripherals/uart' },
      { title: 'LIN & ISO7816 over UART', href: '/docs/peripherals/uart-lin-iso7816' },
      { title: 'SPI', href: '/docs/peripherals/spi' },
      { title: 'QSPI / OSPI (memory-mapped flash)', href: '/docs/peripherals/qspi-ospi' },
      { title: 'I²C', href: '/docs/peripherals/i2c' },
      { title: 'I²C — SMBus & PMBus', href: '/docs/peripherals/smbus' },
      { title: 'CAN (classic)', href: '/docs/peripherals/can' },
      { title: 'CAN-FD', href: '/docs/peripherals/can-fd' },
      { title: 'DMA', href: '/docs/peripherals/dma' },
      { title: 'DMA2D / MDMA (advanced)', href: '/docs/peripherals/dma-advanced' },
      { title: 'Timers & PWM', href: '/docs/peripherals/timers' },
      { title: 'Advanced control timers', href: '/docs/peripherals/timers-advanced' },
      { title: 'ADC / DAC', href: '/docs/peripherals/adc' },
      { title: 'USB device', href: '/docs/peripherals/usb' },
      { title: 'USB host & OTG', href: '/docs/peripherals/usb-host' },
      { title: 'Ethernet MAC', href: '/docs/peripherals/ethernet' },
      { title: 'SDMMC / SDIO', href: '/docs/peripherals/sdmmc' },
    ],
  },
  {
    title: 'Systems',
    key: 'systems',
    intro: 'How real products are built — Wi-Fi routers, smartwatches, drones, EV chargers, thermostats. Block diagrams, software stacks, design tradeoffs.',
    links: [
      { title: 'Overview', href: '/docs/systems/overview' },
      { title: 'Wi-Fi router', href: '/docs/systems/wifi-router' },
      { title: 'Smartwatch / fitness tracker', href: '/docs/systems/smartwatch' },
      { title: 'Drone flight controller', href: '/docs/systems/drone-flight-controller' },
      { title: 'Drone — IMU & sensor fusion', href: '/docs/systems/drone-imu' },
      { title: 'Drone — BLDC ESC', href: '/docs/systems/drone-esc' },
      { title: 'EV charger', href: '/docs/systems/ev-charger' },
      { title: 'EV charger — power stage', href: '/docs/systems/ev-charger-power' },
      { title: 'Smart thermostat', href: '/docs/systems/smart-thermostat' },
      { title: 'Automotive ECU', href: '/docs/systems/automotive-ecu', badge: 'ASIL' },
      { title: 'Automotive — AUTOSAR stack', href: '/docs/systems/autosar' },
      { title: 'Industrial motor drive', href: '/docs/systems/motor-drive' },
      { title: 'Motor drive — FOC algorithm', href: '/docs/systems/motor-foc' },
      { title: 'IoT sensor node', href: '/docs/systems/iot-sensor-node' },
      { title: 'Medical wearable', href: '/docs/systems/medical-wearable' },
      { title: 'Industrial gateway', href: '/docs/systems/industrial-gateway' },
    ],
  },
  {
    title: 'Programming',
    key: 'programming',
    intro: 'C, C++, Rust, assembly. Linker scripts, startup, CMSIS, low-level patterns — plus three hands-on tutorial tracks.',
    links: [
      // ─── C language fundamentals (general-purpose C, foundation) ─────────
      { title: 'C language — 15 lessons', href: '/docs/programming/c-tutorial', badge: 'tutorial', group: 'c-lang-tutorial' },
      { title: 'Lesson 1 — Hello, C', href: '/docs/programming/c-lesson-01-hello', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 2 — Types & literals', href: '/docs/programming/c-lesson-02-types', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 3 — Expressions & operators', href: '/docs/programming/c-lesson-03-expressions', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 4 — Control flow', href: '/docs/programming/c-lesson-04-control-flow', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 5 — Functions', href: '/docs/programming/c-lesson-05-functions', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 6 — Arrays', href: '/docs/programming/c-lesson-06-arrays', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 7 — Pointers', href: '/docs/programming/c-lesson-07-pointers', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 8 — Strings', href: '/docs/programming/c-lesson-08-strings', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 9 — Structs & unions', href: '/docs/programming/c-lesson-09-structs', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 10 — Dynamic memory', href: '/docs/programming/c-lesson-10-dynamic-memory', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 11 — Preprocessor', href: '/docs/programming/c-lesson-11-preprocessor', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 12 — Multi-file projects', href: '/docs/programming/c-lesson-12-multi-file', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 13 — Standard library', href: '/docs/programming/c-lesson-13-stdlib', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 14 — Undefined behavior', href: '/docs/programming/c-lesson-14-ub', nested: true, group: 'c-lang-tutorial' },
      { title: 'Lesson 15 — Modern C (C11/17/23)', href: '/docs/programming/c-lesson-15-modern-c', nested: true, group: 'c-lang-tutorial' },
      // ─── C++ programming ─────────────────────────────────────────────────
      { title: 'C++ programming — 15 lessons', href: '/docs/programming/cpp-tutorial', badge: 'tutorial', group: 'cpp-tutorial' },
      { title: 'Lesson 1 — Hello, C++', href: '/docs/programming/cpp-lesson-01-hello', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 2 — References & namespaces', href: '/docs/programming/cpp-lesson-02-references', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 3 — Classes & RAII', href: '/docs/programming/cpp-lesson-03-classes', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 4 — Inheritance & polymorphism', href: '/docs/programming/cpp-lesson-04-inheritance', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 5 — Templates', href: '/docs/programming/cpp-lesson-05-templates', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 6 — STL containers', href: '/docs/programming/cpp-lesson-06-stl-containers', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 7 — Iterators & algorithms', href: '/docs/programming/cpp-lesson-07-iterators-algorithms', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 8 — Smart pointers', href: '/docs/programming/cpp-lesson-08-smart-pointers', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 9 — Move semantics', href: '/docs/programming/cpp-lesson-09-move-semantics', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 10 — Lambdas', href: '/docs/programming/cpp-lesson-10-lambdas', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 11 — Error handling', href: '/docs/programming/cpp-lesson-11-error-handling', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 12 — Concurrency', href: '/docs/programming/cpp-lesson-12-concurrency', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 13 — Modules (C++20)', href: '/docs/programming/cpp-lesson-13-modules', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 14 — Modern C++23', href: '/docs/programming/cpp-lesson-14-modern', nested: true, group: 'cpp-tutorial' },
      { title: 'Lesson 15 — C++ on Cortex-M', href: '/docs/programming/cpp-lesson-15-embedded', nested: true, group: 'cpp-tutorial' },
      // ─── Bare-metal Cortex-M C (existing — assumes C fluency) ────────────
      { title: 'Bare-metal C tutorial — 10 lessons', href: '/docs/programming/tutorial', badge: 'embedded', group: 'c-tutorial' },
      { title: 'Lesson 1 — Toolchain setup', href: '/docs/programming/tutorial-01-toolchain', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 2 — Bare-metal blink', href: '/docs/programming/tutorial-02-bare-metal', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 3 — Registers in C', href: '/docs/programming/tutorial-03-registers', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 4 — Memory map', href: '/docs/programming/tutorial-04-memory-map', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 5 — Linker script', href: '/docs/programming/tutorial-05-linker-script', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 6 — Interrupts & ISRs', href: '/docs/programming/tutorial-06-interrupts', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 7 — Bit patterns', href: '/docs/programming/tutorial-07-bit-patterns', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 8 — Fixed-point math', href: '/docs/programming/tutorial-08-fixed-point', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 9 — State machines', href: '/docs/programming/tutorial-09-state-machine', nested: true, group: 'c-tutorial' },
      { title: 'Lesson 10 — Ring buffers + DMA', href: '/docs/programming/tutorial-10-ringbuffer-dma', nested: true, group: 'c-tutorial' },
      { title: 'Embedded C patterns', href: '/docs/programming/embedded-c' },
      { title: 'volatile & memory-mapped IO', href: '/docs/programming/volatile-mmio' },
      { title: 'CMSIS-Core', href: '/docs/programming/cmsis' },
      { title: 'CMSIS-DSP', href: '/docs/programming/cmsis-dsp' },
      { title: 'Linker scripts', href: '/docs/programming/linker-scripts' },
      { title: 'Startup & vector table', href: '/docs/programming/startup' },
      { title: 'C++ on Cortex-M', href: '/docs/programming/cpp' },
      { title: 'Rust on Cortex-M', href: '/docs/programming/rust', badge: 'modern' },
      { title: 'Inline assembly', href: '/docs/programming/inline-asm' },
      { title: 'Bare-metal libc & newlib-nano', href: '/docs/programming/libc' },
      { title: 'Bootloaders & DFU', href: '/docs/programming/bootloaders' },
      { title: 'OTA update flow', href: '/docs/programming/ota' },
    ],
  },
  {
    title: 'RTOS',
    key: 'rtos',
    intro: 'FreeRTOS, Zephyr, ThreadX, RT-Thread. Schedulers, IPC, tickless idle, priority inversion — plus a hands-on FreeRTOS tutorial.',
    links: [
      { title: 'RTOS tutorial — 10 lessons', href: '/docs/rtos/tutorial', badge: 'tutorial', group: 'rtos-tutorial' },
      { title: 'Lesson 1 — Why an RTOS', href: '/docs/rtos/tutorial-01-why-rtos', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 2 — Hello FreeRTOS', href: '/docs/rtos/tutorial-02-hello-freertos', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 3 — Tasks', href: '/docs/rtos/tutorial-03-tasks', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 4 — Semaphores', href: '/docs/rtos/tutorial-04-semaphores', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 5 — Mutex & priority inh.', href: '/docs/rtos/tutorial-05-mutex', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 6 — Queues', href: '/docs/rtos/tutorial-06-queues', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 7 — Events & notifications', href: '/docs/rtos/tutorial-07-events-notifications', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 8 — Streams & timers', href: '/docs/rtos/tutorial-08-streams-timers', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 9 — Memory management', href: '/docs/rtos/tutorial-09-memory', nested: true, group: 'rtos-tutorial' },
      { title: 'Lesson 10 — Tickless idle + debug', href: '/docs/rtos/tutorial-10-tickless-debug', nested: true, group: 'rtos-tutorial' },
      { title: 'RTOS landscape', href: '/docs/rtos/landscape' },
      { title: 'Scheduling theory', href: '/docs/rtos/scheduling' },
      { title: 'Priority inversion & inheritance', href: '/docs/rtos/priority-inversion' },
      { title: 'IPC & synchronization primitives', href: '/docs/rtos/ipc' },
      { title: 'Tickless idle', href: '/docs/rtos/tickless' },
      { title: 'FreeRTOS', href: '/docs/rtos/freertos' },
      { title: 'Zephyr', href: '/docs/rtos/zephyr' },
      { title: 'ThreadX (Azure RTOS)', href: '/docs/rtos/threadx' },
      { title: 'RT-Thread', href: '/docs/rtos/rt-thread' },
      { title: 'Safety-certified RTOS', href: '/docs/rtos/safety-rtos' },
    ],
  },
  {
    title: 'Tools',
    key: 'tools',
    intro: 'Compilers, debuggers, probes, IDEs, build systems, simulators.',
    links: [
      { title: 'Toolchain (GCC/LLVM)', href: '/docs/tools/toolchains' },
      { title: 'GDB & on-chip debug', href: '/docs/tools/gdb' },
      { title: 'OpenOCD & probes', href: '/docs/tools/openocd' },
      { title: 'Build systems', href: '/docs/tools/build' },
      { title: 'QEMU & Renode', href: '/docs/tools/sim' },
      { title: 'Semihosting', href: '/docs/tools/semihosting' },
      { title: 'SWO printf & ITM', href: '/docs/tools/swo' },
      { title: 'Profiling & coverage', href: '/docs/tools/profiling' },
      { title: 'Static analysis', href: '/docs/tools/static-analysis' },
      { title: 'Formal methods for firmware', href: '/docs/tools/formal-methods' },
    ],
  },
  {
    title: 'Vendors',
    key: 'vendors',
    intro: 'STM32, NXP, Nordic, RP2040, Renesas, TI, Microchip, Silicon Labs, Infineon — plus GigaDevice, Artery, Nuvoton, Ambiq, Maxim/ADI, NVIDIA Jetson, MediaTek, and Rockchip.',
    links: [
      { title: 'STM32 (ST) — overview', href: '/docs/vendors/stm32' },
      { title: 'STM32 F / G / H mainstream', href: '/docs/vendors/stm32-mainstream' },
      { title: 'STM32 L / U low-power', href: '/docs/vendors/stm32-lowpower' },
      { title: 'STM32 WB / WL wireless', href: '/docs/vendors/stm32-wireless' },
      { title: 'NXP Kinetis & i.MX RT', href: '/docs/vendors/nxp' },
      { title: 'NXP LPC family', href: '/docs/vendors/nxp-lpc' },
      { title: 'Nordic nRF', href: '/docs/vendors/nordic' },
      { title: 'Nordic nRF53 dual-core', href: '/docs/vendors/nordic-nrf53' },
      { title: 'Nordic nRF91 cellular', href: '/docs/vendors/nordic-nrf91' },
      { title: 'Raspberry Pi RP2040 / RP2350', href: '/docs/vendors/raspberry' },
      { title: 'Renesas RA / RX', href: '/docs/vendors/renesas' },
      { title: 'TI Tiva / MSP432', href: '/docs/vendors/ti' },
      { title: 'TI Sitara (Cortex-A + R)', href: '/docs/vendors/ti-sitara' },
      { title: 'Microchip SAM', href: '/docs/vendors/microchip' },
      { title: 'Silicon Labs EFM32 / EFR32', href: '/docs/vendors/silabs' },
      { title: 'Infineon XMC / PSoC', href: '/docs/vendors/infineon' },
      { title: 'Infineon AURIX', href: '/docs/vendors/aurix' },
      // ─── GigaDevice (China) ──────────────────────────────────────────────
      { title: 'GigaDevice GD32 — overview', href: '/docs/vendors/gigadevice' },
      { title: 'GD32F mainstream (M3/M4)', href: '/docs/vendors/gigadevice-gd32f' },
      { title: 'GD32L low-power (M23)', href: '/docs/vendors/gigadevice-gd32l' },
      { title: 'GD32W wireless (M33)', href: '/docs/vendors/gigadevice-gd32w' },
      // ─── Artery (China) ──────────────────────────────────────────────────
      { title: 'Artery AT32 — overview', href: '/docs/vendors/artery' },
      { title: 'AT32F4 mainstream (M4)', href: '/docs/vendors/artery-at32f4' },
      { title: 'AT32M motor / power', href: '/docs/vendors/artery-at32m' },
      // ─── Nuvoton (Taiwan) ────────────────────────────────────────────────
      { title: 'Nuvoton NuMicro — overview', href: '/docs/vendors/nuvoton' },
      { title: 'NuMicro M0 entry-level', href: '/docs/vendors/nuvoton-m0' },
      { title: 'NuMicro M4 mainstream', href: '/docs/vendors/nuvoton-m4' },
      { title: 'NuMicro M23 secure', href: '/docs/vendors/nuvoton-m23' },
      // ─── Ambiq (USA, ultra-low-power) ────────────────────────────────────
      { title: 'Ambiq Apollo — overview', href: '/docs/vendors/ambiq' },
      { title: 'Apollo4 sub-µA M4F', href: '/docs/vendors/ambiq-apollo4' },
      { title: 'Apollo510 / Apollo5 (Helium M55)', href: '/docs/vendors/ambiq-apollo5', badge: 'Helium' },
      // ─── Maxim / Analog Devices ──────────────────────────────────────────
      { title: 'Maxim / ADI MAX32 — overview', href: '/docs/vendors/maxim' },
      { title: 'MAX32 general-purpose M4', href: '/docs/vendors/maxim-max32' },
      { title: 'MAX78000 ML accelerator', href: '/docs/vendors/maxim-max78000', badge: 'AI' },
      // ─── NVIDIA Jetson (Cortex-A edge AI) ────────────────────────────────
      { title: 'NVIDIA Jetson — overview', href: '/docs/vendors/nvidia-jetson' },
      { title: 'Jetson Orin Nano / NX', href: '/docs/vendors/nvidia-jetson-orin-nano' },
      { title: 'Jetson AGX Orin / Thor', href: '/docs/vendors/nvidia-jetson-agx' },
      // ─── MediaTek (Cortex-A IoT + Wi-Fi) ─────────────────────────────────
      { title: 'MediaTek — overview', href: '/docs/vendors/mediatek' },
      { title: 'MediaTek Genio (IoT A-series)', href: '/docs/vendors/mediatek-genio' },
      { title: 'MediaTek Filogic Wi-Fi router', href: '/docs/vendors/mediatek-filogic' },
      // ─── Rockchip (Cortex-A SBC) ─────────────────────────────────────────
      { title: 'Rockchip — overview', href: '/docs/vendors/rockchip' },
      { title: 'Rockchip RK3566 / RK3568', href: '/docs/vendors/rockchip-rk3568' },
      { title: 'Rockchip RK3588 / RK3582', href: '/docs/vendors/rockchip-rk3588' },
    ],
  },
];

export const topNavSections = sections.slice(0, 6); // Architecture → Systems
export const sectionMap = Object.fromEntries(sections.map((s) => [s.key, s]));

export function findLink(href: string) {
  return sections.flatMap((s) => s.links.map((l) => ({ section: s, link: l }))).find((x) => x.link.href === href);
}
