export type NavLink = { title: string; href: string; badge?: string };
export type NavSection = { title: string; key: string; intro: string; links: NavLink[] };

export const sections: NavSection[] = [
  {
    title: 'Architecture',
    key: 'architecture',
    intro: 'ARMv6-M through ARMv9-A. Pipelines, modes, exception models, memory ordering, security extensions.',
    links: [
      { title: 'ARM ISA family', href: '/docs/architecture/isa-family' },
      { title: 'AAPCS & calling conventions', href: '/docs/architecture/aapcs' },
      { title: 'ARMv6-M', href: '/docs/architecture/armv6m' },
      { title: 'ARMv7-M', href: '/docs/architecture/armv7m' },
      { title: 'ARMv8-M', href: '/docs/architecture/armv8m', badge: 'v8-M' },
      { title: 'ARMv8-R', href: '/docs/architecture/armv8r' },
      { title: 'ARMv7-M & ARMv8-M (compare)', href: '/docs/architecture/armv7m-armv8m' },
      { title: 'Exception model', href: '/docs/architecture/exception-model' },
      { title: 'Memory model & barriers', href: '/docs/architecture/memory-model' },
      { title: 'Exclusive monitors', href: '/docs/architecture/exclusive-monitors' },
      { title: 'TrustZone', href: '/docs/architecture/trustzone', badge: 'security' },
      { title: 'TrustZone-M deep dive', href: '/docs/architecture/trustzone-m' },
      { title: 'Debug architecture', href: '/docs/architecture/debug' },
      { title: 'Performance monitoring (PMU)', href: '/docs/architecture/pmu' },
      { title: 'PAC, BTI, MTE (v8.x-A)', href: '/docs/architecture/pac-bti-mte' },
    ],
  },
  {
    title: 'Cortex-M',
    key: 'cortex-m',
    intro: 'Microcontroller-class cores — M0 through M85. Real-time, deterministic, deeply embedded.',
    links: [
      { title: 'Core lineup', href: '/docs/cortex-m/lineup' },
      { title: 'Architecture family compared', href: '/docs/cortex-m/architecture-compare' },
      { title: 'Cortex-M0', href: '/docs/cortex-m/m0' },
      { title: 'Cortex-M0+', href: '/docs/cortex-m/m0plus' },
      { title: 'Cortex-M3', href: '/docs/cortex-m/m3' },
      { title: 'Cortex-M4', href: '/docs/cortex-m/m4' },
      { title: 'Cortex-M7', href: '/docs/cortex-m/m7' },
      { title: 'Cortex-M23', href: '/docs/cortex-m/m23', badge: 'v8-M' },
      { title: 'Cortex-M33', href: '/docs/cortex-m/m33', badge: 'v8-M' },
      { title: 'Cortex-M55', href: '/docs/cortex-m/m55', badge: 'Helium' },
      { title: 'Cortex-M85', href: '/docs/cortex-m/m85', badge: 'Helium' },
      { title: 'NVIC overview', href: '/docs/cortex-m/nvic' },
      { title: 'NVIC registers', href: '/docs/cortex-m/nvic-registers' },
      { title: 'NVIC priority & preemption', href: '/docs/cortex-m/nvic-priority' },
      { title: 'Tail-chain & late-arrival', href: '/docs/cortex-m/tail-chain' },
      { title: 'Vector table', href: '/docs/cortex-m/vector-table' },
      { title: 'SysTick & timing', href: '/docs/cortex-m/systick' },
      { title: 'SCB — System Control Block', href: '/docs/cortex-m/scb' },
      { title: 'MPU on Cortex-M', href: '/docs/cortex-m/mpu' },
      { title: 'FPU on Cortex-M', href: '/docs/cortex-m/fpu' },
      { title: 'Cache & TCM (M7/M55/M85)', href: '/docs/cortex-m/cache-tcm' },
      { title: 'DWT / ITM / ETM', href: '/docs/cortex-m/dwt-itm-etm' },
      { title: 'CoreSight', href: '/docs/cortex-m/coresight' },
      { title: 'Low-power modes', href: '/docs/cortex-m/low-power' },
    ],
  },
  {
    title: 'Cortex-A',
    key: 'cortex-a',
    intro: 'Applications-class cores running rich operating systems. MMU, caches, SMP, virtualization.',
    links: [
      { title: 'Cortex-A overview', href: '/docs/cortex-a/overview' },
      { title: 'ARMv7-A vs ARMv8-A vs ARMv9-A', href: '/docs/cortex-a/isa-compare' },
      { title: 'Boot flow & EL levels', href: '/docs/cortex-a/boot-and-exception-levels' },
      { title: 'MMU & paging', href: '/docs/cortex-a/mmu' },
      { title: 'TLB & address translation', href: '/docs/cortex-a/tlb' },
      { title: 'Caches & coherency', href: '/docs/cortex-a/caches' },
      { title: 'GIC — generic interrupt controller', href: '/docs/cortex-a/gic' },
      { title: 'NEON & SVE', href: '/docs/cortex-a/neon-sve' },
      { title: 'SMP & multiprocessing', href: '/docs/cortex-a/smp' },
      { title: 'Virtualization (EL2 / hypervisors)', href: '/docs/cortex-a/virtualization' },
      { title: 'big.LITTLE & DynamIQ', href: '/docs/cortex-a/big-little' },
      { title: 'PMU & profiling', href: '/docs/cortex-a/pmu' },
    ],
  },
  {
    title: 'Cortex-R',
    key: 'cortex-r',
    intro: 'Hard real-time, safety-critical. Lockstep cores, MPUs, tightly coupled memories.',
    links: [
      { title: 'Cortex-R overview', href: '/docs/cortex-r/overview' },
      { title: 'ARMv7-R vs ARMv8-R', href: '/docs/cortex-r/isa-compare' },
      { title: 'Lockstep & ASIL', href: '/docs/cortex-r/lockstep' },
      { title: 'MPU & TCM on Cortex-R', href: '/docs/cortex-r/mpu-tcm' },
      { title: 'Vectored interrupts', href: '/docs/cortex-r/interrupts' },
      { title: 'ECC & error detection', href: '/docs/cortex-r/ecc' },
      { title: 'Safety standards (ISO 26262 / IEC 61508)', href: '/docs/cortex-r/safety-standards' },
      { title: 'Cortex-R52 cluster mode', href: '/docs/cortex-r/r52-cluster' },
    ],
  },
  {
    title: 'Peripherals',
    key: 'peripherals',
    intro: 'GPIO, UART, SPI, I²C, CAN, USB, Ethernet, DMA, ADC/DAC, timers — pattern-by-pattern.',
    links: [
      { title: 'GPIO', href: '/docs/peripherals/gpio' },
      { title: 'GPIO alternate functions & drive', href: '/docs/peripherals/gpio-af' },
      { title: 'UART', href: '/docs/peripherals/uart' },
      { title: 'LIN & ISO7816 over UART', href: '/docs/peripherals/uart-lin-iso7816' },
      { title: 'SPI', href: '/docs/peripherals/spi' },
      { title: 'QSPI / OSPI (memory-mapped flash)', href: '/docs/peripherals/qspi-ospi' },
      { title: 'I²C', href: '/docs/peripherals/i2c' },
      { title: 'I²C — SMBus & PMBus', href: '/docs/peripherals/smbus' },
      { title: 'CAN (classic)', href: '/docs/peripherals/can' },
      { title: 'CAN-FD', href: '/docs/peripherals/can-fd' },
      { title: 'DMA', href: '/docs/peripherals/dma' },
      { title: 'DMA2D / MDMA (advanced)', href: '/docs/peripherals/dma-advanced' },
      { title: 'Timers & PWM', href: '/docs/peripherals/timers' },
      { title: 'Advanced control timers', href: '/docs/peripherals/timers-advanced' },
      { title: 'ADC / DAC', href: '/docs/peripherals/adc' },
      { title: 'USB device', href: '/docs/peripherals/usb' },
      { title: 'USB host & OTG', href: '/docs/peripherals/usb-host' },
      { title: 'Ethernet MAC', href: '/docs/peripherals/ethernet' },
      { title: 'SDMMC / SDIO', href: '/docs/peripherals/sdmmc' },
    ],
  },
  {
    title: 'Systems',
    key: 'systems',
    intro: 'How real products are built — Wi-Fi routers, smartwatches, drones, EV chargers, thermostats. Block diagrams, software stacks, design tradeoffs.',
    links: [
      { title: 'Overview', href: '/docs/systems/overview' },
      { title: 'Wi-Fi router', href: '/docs/systems/wifi-router' },
      { title: 'Smartwatch / fitness tracker', href: '/docs/systems/smartwatch' },
      { title: 'Drone flight controller', href: '/docs/systems/drone-flight-controller' },
      { title: 'Drone — IMU & sensor fusion', href: '/docs/systems/drone-imu' },
      { title: 'Drone — BLDC ESC', href: '/docs/systems/drone-esc' },
      { title: 'EV charger', href: '/docs/systems/ev-charger' },
      { title: 'EV charger — power stage', href: '/docs/systems/ev-charger-power' },
      { title: 'Smart thermostat', href: '/docs/systems/smart-thermostat' },
      { title: 'Automotive ECU', href: '/docs/systems/automotive-ecu', badge: 'ASIL' },
      { title: 'Automotive — AUTOSAR stack', href: '/docs/systems/autosar' },
      { title: 'Industrial motor drive', href: '/docs/systems/motor-drive' },
      { title: 'Motor drive — FOC algorithm', href: '/docs/systems/motor-foc' },
      { title: 'IoT sensor node', href: '/docs/systems/iot-sensor-node' },
      { title: 'Medical wearable', href: '/docs/systems/medical-wearable' },
      { title: 'Industrial gateway', href: '/docs/systems/industrial-gateway' },
    ],
  },
  {
    title: 'Programming',
    key: 'programming',
    intro: 'C, C++, Rust, assembly. Linker scripts, startup, CMSIS, low-level patterns.',
    links: [
      { title: 'Embedded C patterns', href: '/docs/programming/embedded-c' },
      { title: 'volatile & memory-mapped IO', href: '/docs/programming/volatile-mmio' },
      { title: 'CMSIS-Core', href: '/docs/programming/cmsis' },
      { title: 'CMSIS-DSP', href: '/docs/programming/cmsis-dsp' },
      { title: 'Linker scripts', href: '/docs/programming/linker-scripts' },
      { title: 'Startup & vector table', href: '/docs/programming/startup' },
      { title: 'C++ on Cortex-M', href: '/docs/programming/cpp' },
      { title: 'Rust on Cortex-M', href: '/docs/programming/rust', badge: 'modern' },
      { title: 'Inline assembly', href: '/docs/programming/inline-asm' },
      { title: 'Bare-metal libc & newlib-nano', href: '/docs/programming/libc' },
      { title: 'Bootloaders & DFU', href: '/docs/programming/bootloaders' },
      { title: 'OTA update flow', href: '/docs/programming/ota' },
    ],
  },
  {
    title: 'RTOS',
    key: 'rtos',
    intro: 'FreeRTOS, Zephyr, ThreadX, RT-Thread. Schedulers, IPC, tickless idle, priority inversion.',
    links: [
      { title: 'RTOS landscape', href: '/docs/rtos/landscape' },
      { title: 'Scheduling theory', href: '/docs/rtos/scheduling' },
      { title: 'Priority inversion & inheritance', href: '/docs/rtos/priority-inversion' },
      { title: 'IPC & synchronization primitives', href: '/docs/rtos/ipc' },
      { title: 'Tickless idle', href: '/docs/rtos/tickless' },
      { title: 'FreeRTOS', href: '/docs/rtos/freertos' },
      { title: 'Zephyr', href: '/docs/rtos/zephyr' },
      { title: 'ThreadX (Azure RTOS)', href: '/docs/rtos/threadx' },
      { title: 'RT-Thread', href: '/docs/rtos/rt-thread' },
      { title: 'Safety-certified RTOS', href: '/docs/rtos/safety-rtos' },
    ],
  },
  {
    title: 'Tools',
    key: 'tools',
    intro: 'Compilers, debuggers, probes, IDEs, build systems, simulators.',
    links: [
      { title: 'Toolchain (GCC/LLVM)', href: '/docs/tools/toolchains' },
      { title: 'GDB & on-chip debug', href: '/docs/tools/gdb' },
      { title: 'OpenOCD & probes', href: '/docs/tools/openocd' },
      { title: 'Build systems', href: '/docs/tools/build' },
      { title: 'QEMU & Renode', href: '/docs/tools/sim' },
      { title: 'Semihosting', href: '/docs/tools/semihosting' },
      { title: 'SWO printf & ITM', href: '/docs/tools/swo' },
      { title: 'Profiling & coverage', href: '/docs/tools/profiling' },
      { title: 'Static analysis', href: '/docs/tools/static-analysis' },
      { title: 'Formal methods for firmware', href: '/docs/tools/formal-methods' },
    ],
  },
  {
    title: 'Vendors',
    key: 'vendors',
    intro: 'STM32, NXP, Nordic, RP2040, Renesas, TI, Microchip, Silicon Labs, Infineon.',
    links: [
      { title: 'STM32 (ST) — overview', href: '/docs/vendors/stm32' },
      { title: 'STM32 F / G / H mainstream', href: '/docs/vendors/stm32-mainstream' },
      { title: 'STM32 L / U low-power', href: '/docs/vendors/stm32-lowpower' },
      { title: 'STM32 WB / WL wireless', href: '/docs/vendors/stm32-wireless' },
      { title: 'NXP Kinetis & i.MX RT', href: '/docs/vendors/nxp' },
      { title: 'NXP LPC family', href: '/docs/vendors/nxp-lpc' },
      { title: 'Nordic nRF', href: '/docs/vendors/nordic' },
      { title: 'Nordic nRF53 dual-core', href: '/docs/vendors/nordic-nrf53' },
      { title: 'Nordic nRF91 cellular', href: '/docs/vendors/nordic-nrf91' },
      { title: 'Raspberry Pi RP2040 / RP2350', href: '/docs/vendors/raspberry' },
      { title: 'Renesas RA / RX', href: '/docs/vendors/renesas' },
      { title: 'TI Tiva / MSP432', href: '/docs/vendors/ti' },
      { title: 'TI Sitara (Cortex-A + R)', href: '/docs/vendors/ti-sitara' },
      { title: 'Microchip SAM', href: '/docs/vendors/microchip' },
      { title: 'Silicon Labs EFM32 / EFR32', href: '/docs/vendors/silabs' },
      { title: 'Infineon XMC / PSoC', href: '/docs/vendors/infineon' },
      { title: 'Infineon AURIX', href: '/docs/vendors/aurix' },
    ],
  },
];

export const topNavSections = sections.slice(0, 6); // Architecture → Systems
export const sectionMap = Object.fromEntries(sections.map((s) => [s.key, s]));

export function findLink(href: string) {
  return sections.flatMap((s) => s.links.map((l) => ({ section: s, link: l }))).find((x) => x.link.href === href);
}
